// General converter: merges one or more frontdoor-style workflow outputs
// ({locale:{page:[{es,t}]}}) into src/data/frontdoor.i18n.ts.
// Usage: node scripts/gen-i18n.mjs <output1.json> [<output2.json> ...]
import fs from 'node:fs';

const OUT = new URL('../src/data/frontdoor.i18n.ts', import.meta.url);
const LOCALES = ['en', 'th', 'fr', 'it', 'ch'];
const files = process.argv.slice(2);

const decode = (s) => String(s)
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'");
// Normalize keys so multiline JSX text (with source line breaks + indentation)
// matches the clean string passed at render. Collapse whitespace runs, trim.
const normKey = (s) => decode(s).replace(/\s+/g, ' ').trim();

const merged = {}; // { locale: { page: { es: t } } }
for (const l of LOCALES) merged[l] = {};

let totalPages = new Set();
for (const f of files) {
  if (!fs.existsSync(f) || fs.statSync(f).size === 0) { console.warn('skip (missing/empty):', f); continue; }
  const j = JSON.parse(fs.readFileSync(f, 'utf8'));
  const byLocale = (j.byLocale ? j : (j.result || {})).byLocale || {};
  for (const l of LOCALES) {
    const pages = byLocale[l] || {};
    for (const p of Object.keys(pages)) {
      totalPages.add(p);
      merged[l][p] = merged[l][p] || {};
      for (const pair of (pages[p] || [])) {
        if (pair && pair.es != null) merged[l][p][normKey(pair.es)] = decode(pair.t ?? pair.es);
      }
    }
  }
}

const header = `// ════════════════════════════════════════════════════════════════════════
// Front-door + secondary page translations. Pages keep Spanish inline as
// canonical; \`frontTr(page, locale)\` looks each string up by exact match,
// falling back to Spanish if missing.
//
// Shape: { <locale>: { <pageId>: { "<es string>": "<translation>" } } }
// GENERATED by scripts/gen-i18n.mjs from the i18n translation workflows.
// ════════════════════════════════════════════════════════════════════════

export type FrontdoorI18n = Record<string, Record<string, Record<string, string>>>;

export const frontdoorI18n: FrontdoorI18n = `;

const footer = `;

/** Returns tr(esString) for a given page + locale. ES (or any miss) → the original string.
 *  Lookup is whitespace-insensitive so multiline JSX text matches its clean key. */
export function frontTr(page: string, locale: string) {
  const dict = locale === 'es' ? null : frontdoorI18n[locale]?.[page];
  return (s: string): string => {
    if (!dict) return s;
    const k = s.replace(/\\s+/g, ' ').trim();
    return dict[k] || s;
  };
}
`;

fs.writeFileSync(OUT, header + JSON.stringify(merged, null, 2) + footer, 'utf8');
const report = LOCALES.map((l) => `${l}: ` + [...totalPages].sort().map((p) => `${p}=${Object.keys(merged[l][p] || {}).length}`).join(' ')).join('\n');
console.log(`Merged ${files.length} file(s), ${totalPages.size} pages:\n` + report);
